### ISSUE TITLE
Seems like new `x86_64` images has broken!

### ISSUE THREAD

**Issue by mobin-2008** [chimera-linux/chimera-live#6] opened 2022-11-11 08:10 UTC
Hello. I interested in chimera-linux because that have a simple & very great `targets` Implementation. I try it today but seems like new image (chimera-linux-x86_64-LIVE-20221012-base.iso) has broken! I mean that stuck in both EFI & Legacy mode on booting kernel step. For more info I try chimera with older image (chimera-linux-x86_64-20220912-base.iso) and everything is good!
I attach images & videos about this issue.

Images checksums:
````
1e61ff05c7d1bcc6777c94fa4d1b157275722cf83da82c3656b4acec92883fa1  chimera-linux-x86_64-20220912-base.iso
aa7913140085131028fc670d1a1d07eda470686cab06ebb9c39ff1bcfe7e9a8f  chimera-linux-x86_64-LIVE-20221012-base.iso
````
Runned on Real hardware:
AMD Ryzen 5 3500x
NVIDIA Geforce GTX 1650
ASUS PRIME B450M-A

Images writed into a USB stick. with `dd if=IMAGE of=/dev/sdc bs=1M`

Images & Videos:
pending

**Comment by mobin-2008** [comment] 2022-11-11 08:36
New image on `EFI` Stuck on this point:
![20221111_110052](https://user-images.githubusercontent.com/85447245/201295904-308c2010-0b91-4cf7-bcfe-ac4a9f228b61.jpg)

Older image on `EFI`:

https://user-images.githubusercontent.com/85447245/201298769-2aa12bcb-391d-473f-8e25-2e48cac2aa46.mp4

New image on `Legacy (CSM)` Stuck on this point:
![۲۰۲۲۱۱۱۱_۱۱۰۳۱۸](https://user-images.githubusercontent.com/85447245/201299234-1f33c322-6fe1-42eb-9c2c-db3b399b4c36.jpg)

Older image on `Legacy (CSM)`:

https://user-images.githubusercontent.com/85447245/201299586-6b381999-3024-4ad8-a420-8154e379085f.mp4

I hope it's helpful!

**Comment by q66** [comment] 2022-11-11 13:33
probably has to do with the transition to kernel 6.0 in some way; virtual machines with the latest image boot okay, which complicates things

if you can, it would be very helpful if you tried to generate your own .iso with `mklive.sh` and the latest packages and check if that boots, since the images have an early 6-series kernel and it could have been a regression fixed in a later patch version

otherwise i'll have to set up a native x86_64 computer and try to reproduce it there...

**Comment by q66** [comment] 2022-11-11 13:56
i am currently doing an update to kernel 6.0.8, i will post here when the packages are up for that

**Comment by mobin-2008** [comment] 2022-11-11 14:04
So I create custom iso via `mklive.sh` now?

**Comment by q66** [comment] 2022-11-11 14:12
in ~30 minutes the updated kernel packages should be up for x86_64 (right now you would get 6.0.2)

**Comment by mobin-2008** [comment] 2022-11-11 14:15
I need to download `apk` package manager. Do you know how to install `apk` on Debian? Seems like it's not possible. I think I need to download alpine live image to do it.

**Comment by q66** [comment] 2022-11-11 14:16
you will need apk from git, so alpine will not help

you can compile it from https://gitlab.alpinelinux.org/alpine/apk-tools/

**Comment by q66** [comment] 2022-11-11 14:26
the packages are available now on x86_64

**Comment by q66** [comment] 2022-11-11 15:08
i created a testing image, you can try this if you can't build https://repo.chimera-linux.org/live/testing/chimera-linux-x86_64-LIVE-20221111-base.iso (boots in vm)

**Comment by mobin-2008** [comment] 2022-11-11 15:58
@q66 Thanks. I don't have disk space to build image. Seems like you right and upgrading linux kernel fix this issue!

**Comment by q66** [comment] 2022-11-11 16:05
so it boots now? that's great to hear

i was planning to prepare a new set of images in near future (chimera-live-install has some issues as well, and there have been various updates around the system) so that will address the problem - i will leave this ticket open in the meantime

**Comment by q66** [comment] 2022-11-15 13:19
new images are out, so this is fixed

**Closed as completed by q66** 2022-11-15 13:19 UTC

**Comment by mobin-2008** [comment] 2022-12-08 11:05
@q66 Excuse me but how can I report bugs about a package (pipewire) in chimera-linux? I'm don't find anything about reporting packages bugs in chimera-linux.

**Comment by q66** [comment] 2022-12-08 11:21
cports issue tracker?

**Comment by mobin-2008** [comment] 2022-12-08 11:30
> cports issue tracker?

Thanks
